"""Initial migration

Revision ID: 6fb1735ee4c3
Revises: 
Create Date: 2026-03-19 17:03:32.027341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '6fb1735ee4c3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# * Función DDL(Data Defenition Language)
# * Su función es aplicar cambios en la bd
def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('businessName', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phoneNumber', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_businessName'), 'supplier', ['businessName'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('passwordHash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('basePrice', sa.Float(), nullable=False),
    sa.Column('urlImage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('supplierID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['supplierID'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_name'), 'product', ['name'], unique=False)
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('dateCreate', sa.DateTime(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['userID'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('productID', sa.Integer(), nullable=True),
    sa.Column('actualStock', sa.Integer(), nullable=False),
    sa.Column('minimStock', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['productID'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promotion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('productID', sa.Integer(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=False),
    sa.Column('dateBegin', sa.DateTime(), nullable=False),
    sa.Column('dateEnd', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['productID'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requestdetail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('productID', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('fixedPrice', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['productID'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

# Función para eliminar tablas o para hacer rollback si algo sale mal
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requestdetail')
    op.drop_table('promotion')
    op.drop_table('inventary')
    op.drop_table('request')
    op.drop_index(op.f('ix_product_name'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_supplier_businessName'), table_name='supplier')
    op.drop_table('supplier')
    # ### end Alembic commands ###
